<?php

/**
 * Implementation of hook_menu().
 */
function term_reference_tree_menu(){
  return array(
    'term-reference-tree/%taxonomy_term/%' => array(
      'title' => 'term_reference_tree callback',
      'title callback' => FALSE,
      'page callback' => 'term_reference_tree_page_callback',
      'page arguments' => array(
        1,
        2
      ),
      'delivery callback' => 'ajax_deliver',
      'access callback' => 'term_reference_tree_access_callback',
      'access arguments' => array(
        1
      )
    )
  );
}

/**
 * Callback used to return the additional HTML for a branch in a tree
 */
function term_reference_tree_page_callback($term, $element_id){
  $variables = array(
    'vid' => $term->vid,
    'tid' => $term->tid,
    'element' => array(
      '#id' => $element_id
    )
  );
  return theme('options_tree', $variables);
}

/**
 * Access callback.  Checks that the user has editing privileges for this form.
 */
function term_reference_tree_access_callback($form){
  return TRUE;
}

/**
 * Implements hook_field_widget_info().
 */
function term_reference_tree_field_widget_info(){
  return array(
    'term_reference_tree' => array(
      'label' => 'Term reference tree',
      'field types' => array(
        'taxonomy_term_reference'
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_DEFAULT
      )
    )
  );
}

/**
 * Implements hook_element_info().
 */
function term_reference_tree_element_info(){
  $types = array(
    'options_tree' => array(
      '#input' => true,
      '#theme' => array(
        'options_tree'
      ),
      '#pre_render' => array(
        'form_pre_render_conditional_form_element'
      )
    )
  );
  return $types;
}

/**
 * Implements hook_theme().
 */
function term_reference_tree_theme(){
  return array(
    'options_tree' => array(
      'render element' => 'element'
    ),
    'options_tree_term' => array(
      'term' => 'term',
      'tid' => 'tid',
      'vid' => 'vid'
    ),
    'options_tree_expand_button' => array(
      'field_id' => 'field_id',
      'term' => 'term'
    )
  );
}

/**
 * 
 */
function theme_options_tree_expand_button($variables){
  // Check if the term has any children, if so, we need to return a plus, else
  // we return a blank.
  $children = taxonomy_get_children($variables['term']->tid, $variables['term']->vid);
  $output = '<div id="' . $variables['field_id'] . '__' . $variables['term']->tid . '" class="options_tree_plus ';
  if(count($children)){
    $output .= 'plus';
  }else{
    $output .= 'leaf';
  }
  return $output . '">&nbsp;</div>';
}

/**
 * Returns HTML for a options_tree form element.
 *
 * @param $variables
 * An associative array containing:
 * - element: An associative array containing the properties of the element.
 */
function theme_options_tree($variables){
  if(!isset($variables['vid'])){
    $vocabulary = taxonomy_vocabulary_machine_name_load($variables['element']['#vocabulary']);
    $variables['vid'] = $vocabulary->vid;
    $variables['tid'] = 0;
  }
  // Get the root terms.  These will need to be merged with the ancestors of the
  // "default_value" terms.
  $root_terms = taxonomy_get_tree($variables['vid'], $variables['tid'], 1);
  $output = "<ul>";
  foreach($root_terms as $term){
    $variables['term'] = $term;
    $output .= theme('options_tree_term', $variables);
  }
  return $output . '</ul>';
}

function theme_options_tree_term($variables){
  $checkbox_variables = array(
    'element' => array(
      '#id' => $variables['element']['#id'] . '-' . $variables['term']->tid,
      '#name' => $variables['element']['#id'] . '[]',
      '#return_value' => $variables['term']->tid
    )
  );
  $variables['tid'] = $variables['term']->tid;
  return '<li>' . theme('options_tree_expand_button', array(
    'field_id' => $variables['element']['#id'],
    'term' => $variables['term']
  )) . '<label>' . theme('checkbox', $checkbox_variables) . check_plain($variables['term']->name) . '</label>' . //theme('options_tree', $variables) . 
'</li>';
}

/**
 * Implements hook_widget_field_form().
 */
function term_reference_tree_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element){
  // TODO - Add default values
  // TODO - Enable altering of TID (could be alternative to filtering by a view)
  $default_value = array();
  foreach($items as $item){
    $default_value[] = $item['tid'];
  }
  $element += array(
    '#type' => 'options_tree',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'term_reference_tree') . '/term_reference_tree.css'
      ),
      'js' => array(
        drupal_get_path('module', 'term_reference_tree') . '/term_reference_tree.js' => array(
          'type' => 'file'
        ),
        array(
          'data' => array(
            'term_reference_tree' => array(
              'callback' => url('term-reference-tree')
            )
          ),
          'type' => 'setting'
        )
      )
    ),
    '#multiple' => $field['cardinality'],
    '#vocabulary' => $field['settings']['allowed_values'][0]['vocabulary'],
    '#tid' => 0,
    '#leaves_only' => $instance['widget']['settings']['leaves_only'],
    '#element_validate' => array(
      '_term_reference_tree_widget_validate'
    ),
    '#default_value' => $default_value
  );
  return $element;
}

/**
 * Validates the term reference tree widgets.
 * 
 * This function sets the value of the tree widgets into a form that Drupal
 * can understand, and also checks if the field is required and has been
 * left empty.
 * 
 * @param $element
 * The element to be validated.
 * @param $form_state
 * The state of the form.
 * 
 * @return
 * The validated element.
 */
function _term_reference_tree_widget_validate(&$element, &$form_state){
  // TODO - Add validation.
  $values = array();
  foreach($form_state['input'][$element['#id']] as $tid){
    $values[] = array(
      'tid' => $tid
    );
  }
  form_set_value($element, $values, $form_state);
}